# Generated by Django 5.2.5 on 2025-08-12 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_alter_player_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='email',
            field=models.CharField(error_messages={'unique': 'That email is already registered!'}, max_length=60, unique=True),
        ),
    ]
